name: Deploy Portfolio to GitHub Pages

on:
  push:
    branches: ["v2"] # event starts automation when push to v2 branch

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest # vm to execute build
    steps:
      - name: Checkout
        uses: actions/checkout@v4 # copies repository to vm

      - name: Setup Node
        uses: actions/setup-node@v4 # install node.js on vm
        with:
          node-version: "20"
          cache: 'npm'
      
      - name: Install dependencies # install dependencies
        run: npm install
      
      - name: Build with Next.js # creates static out folder
        run: npm run build
      
      - name: Upload artifact # zips out file as artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./out

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build # deployment needs build job to finish first
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4 # pushes artifact live